{
  "terminal.external.windowsExec": "C:\\Program Files\\Git\\git-bash.exe",
  "workbench.startupEditor": "none",
  "git.enableSmartCommit": true,
  "editor.linkedEditing": true,
  "git.showPushSuccessNotification": true,
  "git.alwaysSignOff": true,
  "git.allowNoVerifyCommit": true,
  "git.autoStash": true,
  "git.autofetch": true,
  "terminal.integrated.sendKeybindingsToShell": true,
  "liveServer.settings.donotVerifyTags": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "explorer.confirmDragAndDrop": false,
  "files.associations": {
    "*.scss": "bat",
    "*.js": "javascriptreact"
  },
  "javascript.implicitProjectConfig.checkJs": true,
  "editor.wordBasedSuggestions": true,
  "emmet.triggerExpansionOnTab": true,
  "security.workspace.trust.enabled": false,

  "explorer.confirmDelete": false,
  "settingsSync.ignoredSettings": [],
  "cSpell.userWords": [
    "Achol",
    "Akhi",
    "Aklima",
    "Akter",
    "Deposite",
    "dialoge",
    "Farhana",
    "Fata",
    "Fontend",
    "Hasan",
    "Hashi",
    "indigator",
    "Kanye",
    "Khatiza",
    "Khushi",
    "Mostakim",
    "OPPO",
    "Orpita",
    "pagli",
    "Preebook",
    "Rasel",
    "Rokibul",
    "rokibul's",
    "sejuty",
    "Shipon",
    "stevekaku",
    "Sufian",
    "Sumpa",
    "Vission"
  ],
  "editor.formatOnSave": true,
  "tabnine.experimentalAutoImports": true,
  "quokka.automaticRestart": true,
  "quokka.compactMessageOutput": true,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.rulers": [],
  "terminal-tools.dependencies": [],
  "emmet.triggerExpansionOnTab": true,
  "tailwindCSS.emmetCompletions": true,
  "emmet.showSuggestionsAsSnippets": true,
  "bracketPairColorizer.highlightActiveScope": true,
  "bracketPairColorizer.showBracketsInRuler": true,
  "bracketPairColorizer.showBracketsInGutter": true,
  "editor.autoClosingDelete": "always",
  "editor.autoClosingOvertype": "always",
  "editor.autoClosingQuotes": "always",
  "[javascript]": {
    "editor.autoClosingBrackets": "always",
    "editor.defaultFormatter": "HookyQR.beautify"
  },
  "editor.wordWrap": "on",
  "editor.inlineSuggest.enabled": true,
  "html.format.endWithNewline": true,
  "html.format.templating": true,
  "eslint.format.enable": true,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "liveServer.settings.port": 3000,

  "emojisense.languages": {
    "plaintext": {
      "markupCompletionsEnabled": true,
      "emojiDecoratorsEnabled": true
    },
    "javascript.validate.enable": false,
    "abap": true,
    "bat": true,
    "bibtex": true,
    "clojure": true,
    "coffeescript": true,
    "c": true,
    "cpp": true,
    "csharp": true,
    "css": true,
    "diff": true,
    "dockerfile": true,
    "fsharp": true,
    "git-commit": true,
    "git-rebase": true,
    "go": true,
    "groovy": true,
    "handlebars": true,
    "html": true,
    "ini": true,
    "java": true,
    "javascript": true,
    "javascriptreact": true,
    "json": true,
    "jsonc": true,
    "latex": true,
    "less": true,
    "lua": true,
    "makefile": true,
    "markdown": true,
    "objective-c": true,
    "objective-cpp": true,
    "perl6": true,
    "php": true,
    "powershell": true,
    "jade": true,
    "python": true,
    "r": true,
    "razor": true,
    "ruby": true,
    "rust": true,
    "scss": true,
    "sass": true,
    "shaderlab": true,
    "shellscript": true,
    "sql": true,
    "swift": true,
    "typescript": true,
    "typescriptreact": true,
    "tex": true,
    "vb": true,
    "xml": true,
    "xsl": true,
    "yaml": true,
    "scminput": true,
    "git-commit": true
  },
  "breadcrumbs.enabled": false,
  "editor.renderWhitespace": "none",
  "editor.codeActionsOnSave": null,
  "terminal.integrated.enablePersistentSessions": false,
  "bracketPairColorizer.forceIterationColorCycle": true,
  "bracketPairColorizer.forceUniqueOpeningColor": true,
  "terminal.integrated.copyOnSelection": true,
  "terminal.integrated.detectLocale": "off",
  "terminal.integrated.enableBell": true,
  "terminal.integrated.experimentalLinkProvider": false,
  "files.autoSave": "afterDelay",
  "security.workspace.trust.banner": "never",
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "editor.minimap.enabled": false,
  "editor.foldingImportsByDefault": true,
  "fontAwesomeAutocomplete.disableTriggerWordAutoClearPatterns": [],
  "typescript.preferences.importModuleSpecifierEnding": "js",
  "javascript.preferences.importModuleSpecifierEnding": "js",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnType": true,
  "editor.formatOnPaste": true,
  "terminal.integrated.fontSize": 16,
  "window.zoomLevel": 2,
  "diffEditor.wordWrap": "on",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "bracketPairColorizer.depreciation-notice": false
}
{
  "terminal.external.windowsExec": "C:\\Program Files\\Git\\git-bash.exe",
  "workbench.startupEditor": "none",
  "git.enableSmartCommit": true,
  "editor.linkedEditing": true,
  "git.showPushSuccessNotification": true,
  "git.alwaysSignOff": true,
  "git.allowNoVerifyCommit": true,
  "git.autoStash": true,
  "git.autofetch": true,
  "terminal.integrated.sendKeybindingsToShell": true,
  "liveServer.settings.donotVerifyTags": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "explorer.confirmDragAndDrop": false,
  "files.associations": {
    "*.scss": "bat",
    "*.js": "javascriptreact"
  },
  "javascript.implicitProjectConfig.checkJs": true,
  "editor.wordBasedSuggestions": true,
  "emmet.triggerExpansionOnTab": true,
  "security.workspace.trust.enabled": false,

  "explorer.confirmDelete": false,
  "settingsSync.ignoredSettings": [],
  "cSpell.userWords": [
    "Achol",
    "Akhi",
    "Aklima",
    "Akter",
    "Deposite",
    "dialoge",
    "Farhana",
    "Fata",
    "Fontend",
    "Hasan",
    "Hashi",
    "indigator",
    "Kanye",
    "Khatiza",
    "Khushi",
    "Mostakim",
    "OPPO",
    "Orpita",
    "pagli",
    "Preebook",
    "Rasel",
    "Rokibul",
    "rokibul's",
    "sejuty",
    "Shipon",
    "stevekaku",
    "Sufian",
    "Sumpa",
    "Vission"
  ],
  "editor.formatOnSave": true,
  "tabnine.experimentalAutoImports": true,
  "quokka.automaticRestart": true,
  "quokka.compactMessageOutput": true,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.rulers": [],
  "terminal-tools.dependencies": [],
  "emmet.triggerExpansionOnTab": true,
  "tailwindCSS.emmetCompletions": true,
  "emmet.showSuggestionsAsSnippets": true,
  "bracketPairColorizer.highlightActiveScope": true,
  "bracketPairColorizer.showBracketsInRuler": true,
  "bracketPairColorizer.showBracketsInGutter": true,
  "editor.autoClosingDelete": "always",
  "editor.autoClosingOvertype": "always",
  "editor.autoClosingQuotes": "always",
  "[javascript]": {
    "editor.autoClosingBrackets": "always",
    "editor.defaultFormatter": "HookyQR.beautify"
  },
  "editor.wordWrap": "on",
  "editor.inlineSuggest.enabled": true,
  "html.format.endWithNewline": true,
  "html.format.templating": true,
  "eslint.format.enable": true,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "liveServer.settings.port": 3000,

  "emojisense.languages": {
    "plaintext": {
      "markupCompletionsEnabled": true,
      "emojiDecoratorsEnabled": true
    },
    "javascript.validate.enable": false,
    "abap": true,
    "bat": true,
    "bibtex": true,
    "clojure": true,
    "coffeescript": true,
    "c": true,
    "cpp": true,
    "csharp": true,
    "css": true,
    "diff": true,
    "dockerfile": true,
    "fsharp": true,
    "git-commit": true,
    "git-rebase": true,
    "go": true,
    "groovy": true,
    "handlebars": true,
    "html": true,
    "ini": true,
    "java": true,
    "javascript": true,
    "javascriptreact": true,
    "json": true,
    "jsonc": true,
    "latex": true,
    "less": true,
    "lua": true,
    "makefile": true,
    "markdown": true,
    "objective-c": true,
    "objective-cpp": true,
    "perl6": true,
    "php": true,
    "powershell": true,
    "jade": true,
    "python": true,
    "r": true,
    "razor": true,
    "ruby": true,
    "rust": true,
    "scss": true,
    "sass": true,
    "shaderlab": true,
    "shellscript": true,
    "sql": true,
    "swift": true,
    "typescript": true,
    "typescriptreact": true,
    "tex": true,
    "vb": true,
    "xml": true,
    "xsl": true,
    "yaml": true,
    "scminput": true,
    "git-commit": true
  },
  "breadcrumbs.enabled": false,
  "editor.renderWhitespace": "none",
  "editor.codeActionsOnSave": null,
  "terminal.integrated.enablePersistentSessions": false,
  "bracketPairColorizer.forceIterationColorCycle": true,
  "bracketPairColorizer.forceUniqueOpeningColor": true,
  "terminal.integrated.copyOnSelection": true,
  "terminal.integrated.detectLocale": "off",
  "terminal.integrated.enableBell": true,
  "terminal.integrated.experimentalLinkProvider": false,
  "files.autoSave": "afterDelay",
  "security.workspace.trust.banner": "never",
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "editor.minimap.enabled": false,
  "editor.foldingImportsByDefault": true,
  "fontAwesomeAutocomplete.disableTriggerWordAutoClearPatterns": [],
  "typescript.preferences.importModuleSpecifierEnding": "js",
  "javascript.preferences.importModuleSpecifierEnding": "js",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnType": true,
  "editor.formatOnPaste": true,
  "terminal.integrated.fontSize": 16,
  "window.zoomLevel": 2,
  "diffEditor.wordWrap": "on",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "bracketPairColorizer.depreciation-notice": false
}
